-- Add missing raw_text column to bank_transactions
-- This stores the original unprocessed transaction text from imports
ALTER TABLE bank_transactions 
ADD COLUMN IF NOT EXISTS raw_text TEXT;

-- Add index for raw_text searches (useful for debugging and analysis)
CREATE INDEX IF NOT EXISTS idx_bank_transactions_raw_text 
ON bank_transactions USING gin(to_tsvector('english', raw_text))
WHERE raw_text IS NOT NULL;

-- Create cash_forecasts table for forecast engine persistence
-- Stores 13-week cash flow forecasts for historical tracking and analysis
CREATE TABLE IF NOT EXISTS cash_forecasts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    week_number INTEGER NOT NULL CHECK (week_number >= 1 AND week_number <= 13),
    baseline NUMERIC(20,2) NOT NULL,
    upper_bound NUMERIC(20,2),
    lower_bound NUMERIC(20,2),
    forecast_balance NUMERIC(20,2),
    confidence NUMERIC(5,2),
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for cash_forecasts
CREATE INDEX idx_cash_forecasts_tenant 
ON cash_forecasts(tenant_id);

CREATE INDEX idx_cash_forecasts_generated 
ON cash_forecasts(tenant_id, generated_at DESC);

-- Unique constraint: one forecast per tenant per generation time per week
CREATE UNIQUE INDEX idx_cash_forecasts_tenant_week 
ON cash_forecasts(tenant_id, generated_at, week_number);

-- Comments for documentation
COMMENT ON TABLE cash_forecasts IS 
'Persisted 13-week cash flow forecasts for historical tracking and trend analysis. Generated by the forecast engine.';

COMMENT ON COLUMN cash_forecasts.week_number IS 
'Week number in forecast (1-13), where 1 is the current week';

COMMENT ON COLUMN cash_forecasts.baseline IS 
'Baseline forecast amount for this week';

COMMENT ON COLUMN cash_forecasts.upper_bound IS 
'Upper confidence bound (baseline + 1 standard deviation)';

COMMENT ON COLUMN cash_forecasts.lower_bound IS 
'Lower confidence bound (baseline - 1 standard deviation)';

COMMENT ON COLUMN cash_forecasts.forecast_balance IS 
'Projected cash balance at end of week';

COMMENT ON COLUMN cash_forecasts.confidence IS 
'Confidence score (0-100) based on historical data quality';

COMMENT ON COLUMN cash_forecasts.metadata IS 
'Additional forecast metadata (e.g., assumptions, data sources, algorithm version)';
