export const PRICING_PLANS = [
  {
    key: "starter",
    name_en: "Starter",
    name_ar: "المبتدئ",
    price: 0,
    currency: "SAR",
    period_en: "Free forever",
    period_ar: "مجاني للأبد",
    description_en: "For solo founders exploring cash flow management.",
    description_ar: "لرواد الأعمال المنفردين لاستكشاف إدارة التدفق النقدي.",
    features_en: [
      "1 bank account",
      "2 users",
      "CSV import",
      "30-day forecast",
      "Basic alerts",
    ],
    features_ar: [
      "حساب بنكي واحد",
      "مستخدمان",
      "استيراد CSV",
      "توقعات ٣٠ يومًا",
      "تنبيهات أساسية",
    ],
    cta_en: "Get Started",
    cta_ar: "ابدأ الآن",
    highlighted: false,
  },
  {
    key: "core",
    name_en: "Core",
    name_ar: "الأساسي",
    price: 499,
    currency: "SAR",
    period_en: "/month",
    period_ar: "/شهر",
    description_en: "For growing SMEs that need real-time visibility.",
    description_ar: "للشركات الصغيرة والمتوسطة النامية التي تحتاج رؤية فورية.",
    features_en: [
      "5 bank accounts",
      "10 users",
      "CSV + bank sync",
      "13-week forecast",
      "AI alerts & daily brief",
      "Monthly reports",
    ],
    features_ar: [
      "٥ حسابات بنكية",
      "١٠ مستخدمين",
      "CSV + مزامنة بنكية",
      "توقعات ١٣ أسبوعًا",
      "تنبيهات ذكية وملخص يومي",
      "تقارير شهرية",
    ],
    cta_en: "Start Free Trial",
    cta_ar: "ابدأ تجربة مجانية",
    highlighted: true,
  },
  {
    key: "pro",
    name_en: "Pro",
    name_ar: "الاحترافي",
    price: 1499,
    currency: "SAR",
    period_en: "/month",
    period_ar: "/شهر",
    description_en: "For established businesses needing full automation.",
    description_ar: "للشركات القائمة التي تحتاج أتمتة كاملة.",
    features_en: [
      "20 bank accounts",
      "50 users",
      "All integrations",
      "Scenario analysis",
      "Board-ready reports",
      "WhatsApp brief",
      "Priority support",
    ],
    features_ar: [
      "٢٠ حساب بنكي",
      "٥٠ مستخدم",
      "جميع التكاملات",
      "تحليل السيناريوهات",
      "تقارير جاهزة لمجلس الإدارة",
      "ملخص واتساب",
      "دعم أولوية",
    ],
    cta_en: "Start Free Trial",
    cta_ar: "ابدأ تجربة مجانية",
    highlighted: false,
  },
  {
    key: "enterprise",
    name_en: "Enterprise",
    name_ar: "المؤسسات",
    price: null,
    currency: "SAR",
    period_en: "Custom",
    period_ar: "مخصص",
    description_en: "For large organizations and accounting firms.",
    description_ar: "للمؤسسات الكبيرة وشركات المحاسبة.",
    features_en: [
      "Unlimited everything",
      "Custom integrations",
      "Dedicated support",
      "SLA guarantee",
      "On-premise option",
      "White-label available",
    ],
    features_ar: [
      "كل شيء غير محدود",
      "تكاملات مخصصة",
      "دعم مخصص",
      "ضمان SLA",
      "خيار محلي",
      "علامة بيضاء متاحة",
    ],
    cta_en: "Contact Sales",
    cta_ar: "تواصل مع المبيعات",
    highlighted: false,
  },
] as const;
