export const PRICING_PLANS = [
  {
    key: "starter",
    name_en: "Starter",
    name_ar: "المبتدئ",
    price: 0,
    currency: "SAR",
    period_en: "Free forever",
    period_ar: "مجاني للأبد",
    description_en: "For solo founders exploring cash flow management.",
    description_ar: "لرواد الأعمال المنفردين لاستكشاف إدارة التدفق النقدي.",
    features_en: [
      "1 bank account",
      "2 users",
      "CSV import",
      "30-day forecast",
      "Basic alerts",
    ],
    features_ar: [
      "حساب بنكي واحد",
      "مستخدمان",
      "استيراد CSV",
      "توقعات ٣٠ يومًا",
      "تنبيهات أساسية",
    ],
    cta_en: "Get Started",
    cta_ar: "ابدأ الآن",
    highlighted: false,
  },
  {
    key: "core",
    name_en: "Core",
    name_ar: "الأساسي",
    price: 499,
    currency: "SAR",
    period_en: "/month",
    period_ar: "/شهر",
    description_en: "For growing SMEs that need real-time visibility.",
    description_ar: "للشركات الصغيرة والمتوسطة النامية التي تحتاج رؤية فورية.",
    features_en: [
      "5 bank accounts",
      "10 users",
      "CSV + bank sync",
      "13-week forecast",
      "AI alerts & daily brief",
      "Monthly reports",
    ],
    features_ar: [
      "٥ حسابات بنكية",
      "١٠ مستخدمين",
      "CSV + مزامنة بنكية",
      "توقعات ١٣ أسبوعًا",
      "تنبيهات ذكية وملخص يومي",
      "تقارير شهرية",
    ],
    cta_en: "Start Free Trial",
    cta_ar: "ابدأ تجربة مجانية",
    highlighted: true,
  },
  {
    key: "pro",
    name_en: "Pro",
    name_ar: "الاحترافي",
    price: 1499,
    currency: "SAR",
    period_en: "/month",
    period_ar: "/شهر",
    description_en: "For established businesses needing full automation.",
    description_ar: "للشركات القائمة التي تحتاج أتمتة كاملة.",
    features_en: [
      "20 bank accounts",
      "50 users",
      "All integrations",
      "Scenario analysis",
      "Board-ready reports",
      "WhatsApp brief",
      "Priority support",
    ],
    features_ar: [
      "٢٠ حساب بنكي",
      "٥٠ مستخدم",
      "جميع التكاملات",
      "تحليل السيناريوهات",
      "تقارير جاهزة لمجلس الإدارة",
      "ملخص واتساب",
      "دعم أولوية",
    ],
    cta_en: "Start Free Trial",
    cta_ar: "ابدأ تجربة مجانية",
    highlighted: false,
  },
] as const;

export const ENTERPRISE_PLAN = {
  key: "enterprise",
  name_en: "Enterprise",
  name_ar: "حلول المؤسسات والمجموعات",
  tagline_en: "Built for holding companies, conglomerates & accounting firms managing multiple entities",
  tagline_ar: "مصمم للشركات القابضة والمجموعات ومكاتب المحاسبة التي تدير كيانات متعددة",
  cta_en: "Request a Custom Demo",
  cta_ar: "اطلب عرضاً مخصصاً",
  cta2_en: "Talk to Sales",
  cta2_ar: "تحدث مع المبيعات",
  pillars: [
    {
      icon: "building" as const,
      title_en: "Multi-Entity Consolidation",
      title_ar: "توحيد الكيانات المتعددة",
      desc_en: "Real-time consolidated view across all subsidiaries, branches, and legal entities. Inter-company transfers in one click.",
      desc_ar: "رؤية مجمّعة لحظية عبر جميع الشركات التابعة والفروع والكيانات القانونية. تحويلات بين الشركات بنقرة واحدة.",
    },
    {
      icon: "shield" as const,
      title_en: "Enterprise Security & Compliance",
      title_ar: "أمان وامتثال المؤسسات",
      desc_en: "SSO/SAML, role-based access per entity, full audit trail. Compliant with SAMA, QCB, and CBUAE regulations.",
      desc_ar: "SSO/SAML، صلاحيات حسب الكيان، سجل مراجعة كامل. متوافق مع متطلبات ساما والمركزي القطري والمركزي الإماراتي.",
    },
    {
      icon: "brain" as const,
      title_en: "AI Agents at Scale",
      title_ar: "وكلاء ذكاء اصطناعي على نطاق واسع",
      desc_en: "Dedicated AI agents per entity: automated collections, risk alerts, and CFO-grade decision support across your portfolio.",
      desc_ar: "وكلاء ذكاء اصطناعي مخصصون لكل كيان: تحصيل آلي، تنبيهات مخاطر، ودعم قرارات بمستوى CFO عبر محفظتك.",
    },
    {
      icon: "headset" as const,
      title_en: "Dedicated Success Team",
      title_ar: "فريق نجاح مخصص",
      desc_en: "Named account manager, custom onboarding, SLA-backed support, and quarterly business reviews.",
      desc_ar: "مدير حساب مخصص، إعداد مخصص، دعم بضمان SLA، ومراجعات أعمال ربع سنوية.",
    },
  ],
  stats: [
    { value_en: "500+", value_ar: "٥٠٠+", label_en: "Entities managed", label_ar: "كيان مُدار" },
    { value_en: "99.9%", value_ar: "٩٩.٩٪", label_en: "Uptime SLA", label_ar: "ضمان وقت التشغيل" },
    { value_en: "< 2h", value_ar: "< ساعتين", label_en: "Support response", label_ar: "زمن استجابة الدعم" },
    { value_en: "40%", value_ar: "٤٠٪", label_en: "Avg. time saved", label_ar: "متوسط الوقت الموفّر" },
  ],
  logos_label_en: "Trusted by leading GCC enterprises",
  logos_label_ar: "موثوق من قبل مؤسسات الخليج الرائدة",
} as const;
