"use client";

import { useState, useEffect } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Bot, RefreshCw } from "lucide-react";
import { Button } from "@/components/shared/ui/button";
import { Skeleton } from "@/components/shared/ui/skeleton";
import { useI18n } from "@/lib/i18n/context";
import { useTenant } from "@/lib/hooks/use-tenant";
import { RecommendedActionsPanel } from "@/components/ai/agents/RecommendedActionsPanel";
import { DocumentsList } from "@/components/documents/DocumentsList";
// TODO: Restore hooks when agent components are properly structured

type Agent = any;
type BriefItem = any;

export default function AgentsPage() {
  const { locale, dir } = useI18n();
  const { currentTenant } = useTenant();
  const qc = useQueryClient();
  const isAr = locale === "ar";
  const [today, setToday] = useState("");

  // TODO: Restore when agent hooks are available
  // const { data: agents = [], isLoading: agentsLoading } = useAgents(currentTenant?.id);
  // const { data: brief = [], isLoading: briefLoading } = useBriefFeed(currentTenant?.id);
  const agents: Agent[] = [];
  const agentsLoading = false;
  const brief: BriefItem[] = [];
  const briefLoading = false;

  useEffect(() => {
    setToday(
      new Date().toLocaleDateString(
        locale === "ar" ? "ar-SA" : "en-GB",
        { weekday: "long", day: "numeric", month: "long", year: "numeric" }
      )
    );
  }, [locale]);

  const handleRefresh = () => {
    qc.invalidateQueries({ queryKey: ["agents"] });
    qc.invalidateQueries({ queryKey: ["brief"] });
  };

  return (
    <div dir={dir} className="flex flex-col h-full overflow-y-auto" data-page-full>
      {/* ── Page header ── */}
      <div className="flex items-center justify-between px-6 py-3 border-b bg-card shrink-0">
        <div className="flex items-center gap-2">
          <Bot className="h-4 w-4 text-muted-foreground" />
          <h1 className="text-sm font-semibold">
            {isAr ? "مركز الوكلاء الذكيين" : "AI Automation Hub"}
          </h1>
        </div>
        <Button
          size="sm"
          variant="ghost"
          className="h-7 w-7 p-0"
          onClick={handleRefresh}
          aria-label={isAr ? "تحديث" : "Refresh"}
        >
          <RefreshCw className="h-3.5 w-3.5" />
        </Button>
      </div>

      <div className="p-6 space-y-8">
        {/* ── Agent cards grid ── */}
        <section>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
            {isAr ? "الوكلاء" : "Agents"}
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {agentsLoading
              ? Array.from({ length: 3 }).map((_, i) => (
                  <Skeleton key={i} className="h-64 rounded-md" />
                ))
              : agents.length > 0 ? agents.map((agent) => (
                  <div key={agent.id} className="p-4 border rounded-md">
                    Agent: {agent.name}
                  </div>
                )) : (
                  <div className="col-span-3 text-center py-8 text-muted-foreground text-sm">
                    {isAr ? "لا توجد وكلاء متاحة" : "No agents available"}
                  </div>
                )}
          </div>
        </section>

        {/* ── Recommended Actions ── */}
        <section>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
            {isAr ? "الإجراءات الموصى بها" : "Recommended Actions"}
          </p>
          <RecommendedActionsPanel />
        </section>

        {/* ── Documents ── */}
        <section>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-4">
            {isAr ? "المستندات" : "Documents"}
          </p>
          <DocumentsList />
        </section>

        {/* ── Morning brief ── */}
        <section>
          <div className="flex items-center justify-between mb-4">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              {isAr ? "الملخص الصباحي اليومي" : "Daily Morning Brief"}
            </p>
            <span className="text-xs text-muted-foreground tabular">{today}</span>
          </div>

          <div className="rounded-md border bg-card overflow-hidden">
            {/* Brief header bar */}
            <div className="flex items-center gap-2 px-5 py-2.5 border-b bg-muted/40">
              <Bot className="h-3.5 w-3.5 text-muted-foreground" />
              <span className="text-xs text-muted-foreground">
                {isAr
                  ? "مُولَّد بواسطة مستشار · مُدخلات من رقيب ومتوقع"
                  : "Generated by Mustashar · inputs from Raqib & Mutawaqi'"}
              </span>
            </div>

            <div className="p-4">
              {briefLoading ? (
                <Skeleton className="h-32 w-full" />
              ) : brief.length > 0 ? (
                <div>{isAr ? "محتوى الملخص" : "Brief content"}</div>
              ) : (
                <p className="text-sm text-muted-foreground text-center py-8">
                  {isAr ? "لا يوجد ملخص متاح" : "No brief available"}
                </p>
              )}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
